On alignment n.0: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.8: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.17: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.22: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.30: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.63: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.68: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.69: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.75: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.79: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.81: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.82: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.83: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.84: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.85: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.86: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.87: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.88: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.89: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.90: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.91: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.92: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.93: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.94: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.95: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.96: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.97: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.98: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.99: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.100: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.101: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.102: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.103: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.104: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.105: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.106: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.107: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.108: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.109: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.110: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.111: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.112: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.114: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.115: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.116: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.117: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.118: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.119: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.120: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.121: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.122: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.123: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.124: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.125: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.126: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.127: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.128: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.129: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.130: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.131: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.132: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.133: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.134: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.135: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.136: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.137: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.138: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.139: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.140: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.141: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.142: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.143: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.144: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.145: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.146: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.147: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.148: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.149: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.150: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.151: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.152: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.153: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.154: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.155: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.156: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.157: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.158: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.159: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.160: Error: Chain A not found in ./Dataset/2z9q_A.pdb
On alignment n.167: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.176: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.181: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.189: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.222: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.227: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.228: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.234: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.238: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.245: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.254: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.259: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.267: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.300: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.305: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.306: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.312: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.316: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.322: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.331: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.336: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.344: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.377: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.382: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.383: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.389: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.393: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.398: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.407: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.412: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.420: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.453: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.458: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.459: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.465: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.469: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.473: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.482: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.487: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.495: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.528: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.533: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.534: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.540: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.544: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.547: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.556: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.561: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.569: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.602: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.607: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.608: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.614: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.618: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.620: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.629: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.634: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.642: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.675: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.680: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.681: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.687: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.691: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.693: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.694: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.695: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.696: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.697: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.698: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.699: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.700: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.701: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.701: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.702: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.703: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.704: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.705: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.706: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.707: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.708: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.709: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.710: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.711: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.712: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.713: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.714: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.715: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.716: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.718: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.719: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.720: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.721: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.722: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.723: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.724: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.725: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.726: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.727: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.728: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.729: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.730: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.731: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.732: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.733: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.734: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.735: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.736: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.737: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.738: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.739: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.740: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.741: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.742: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.743: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.744: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.745: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.746: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.747: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.748: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.749: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.750: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.751: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.752: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.753: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.754: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.755: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.756: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.757: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.758: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.759: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.760: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.761: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.762: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.763: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.764: Error: Structure ./Dataset/4v4w_A.pdb longer than 500 nucleotides
On alignment n.772: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.777: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.785: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.818: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.823: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.824: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.830: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.834: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.842: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.847: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.855: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.888: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.893: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.894: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.900: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.904: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.911: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.916: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.924: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.957: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.962: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.963: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.969: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.973: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.979: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.984: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.992: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.1025: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.1030: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.1031: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1037: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.1041: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1046: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1051: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1059: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.1092: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.1097: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.1098: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1104: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.1108: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1112: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1117: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1125: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.1158: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.1163: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.1164: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1170: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.1174: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1177: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1182: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1190: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.1223: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.1228: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.1229: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1235: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.1239: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1241: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1246: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1254: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.1287: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.1292: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.1293: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1299: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.1303: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1305: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1306: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1307: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1308: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1309: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1310: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1311: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1312: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1313: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1314: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1315: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1316: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1317: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.1318: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1319: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1321: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1322: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1323: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1324: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1325: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1326: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1327: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1328: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1329: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1330: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1331: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1332: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1333: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1334: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1335: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1336: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1337: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1338: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1339: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1340: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1341: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1342: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1343: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1344: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1345: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1346: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1347: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1348: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1349: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1350: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.1351: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1352: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1353: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1354: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1355: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.1356: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1357: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1358: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1359: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1360: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1361: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1362: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.1363: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1364: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1365: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1366: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1367: Error: Structure ./Dataset/4ujc_A.pdb longer than 500 nucleotides
On alignment n.1371: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1379: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.1412: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.1417: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.1418: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1424: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.1428: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1432: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1440: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.1473: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.1478: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.1479: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1485: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.1489: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1492: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1500: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.1533: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.1538: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.1539: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1545: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.1549: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1551: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1559: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.1592: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.1597: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.1598: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1604: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.1608: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1610: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1611: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1612: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1613: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1614: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1615: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1616: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1617: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1618: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1619: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1621: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1622: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1623: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1624: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1625: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1626: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1627: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1628: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1629: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1630: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1631: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1632: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1633: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1634: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1635: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1636: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1637: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1638: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1639: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1640: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1641: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1642: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1643: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1644: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1645: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1646: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1647: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1648: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1649: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1650: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1651: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1652: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1653: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1654: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1655: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1656: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1657: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1658: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1659: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1660: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1661: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1662: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1663: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1664: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1665: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1666: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1667: Error: Chain 1 not found in ./Dataset/5lzy_1_SA.pdb
On alignment n.1674: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.1707: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.1712: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.1713: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1719: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.1723: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1730: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.1763: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.1768: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.1769: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1775: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.1779: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1785: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.1818: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.1823: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.1824: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1830: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.1834: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1839: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.1872: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.1877: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.1878: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1884: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.1888: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1892: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.1925: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.1930: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.1931: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1937: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.1941: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1944: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.1977: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.1982: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.1983: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1989: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.1993: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.1995: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2028: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.2033: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.2034: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2040: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.2044: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2046: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2047: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2049: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2050: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2051: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2052: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2053: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2054: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2055: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2056: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2057: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2058: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2059: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2060: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2061: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2062: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2063: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2064: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2065: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2066: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2067: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2068: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2069: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2070: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2071: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2072: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2073: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2074: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2075: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2076: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2077: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2078: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2079: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2080: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2081: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2082: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2083: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2084: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2085: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2086: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2087: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2088: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2089: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2090: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2091: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2092: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2093: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2094: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2095: Error: Chain Y not found in ./Dataset/3ep2_Y.pdb
On alignment n.2127: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.2132: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.2133: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2139: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.2143: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2175: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.2180: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.2181: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2187: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.2191: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2268: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.2273: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.2274: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2280: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.2284: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2313: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.2318: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.2319: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2325: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.2329: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2357: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.2362: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.2363: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2369: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.2373: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2400: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.2405: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.2406: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2412: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.2416: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2442: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.2447: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.2448: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2454: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.2458: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2483: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.2488: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.2489: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2495: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.2499: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2523: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.2528: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.2529: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2535: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.2539: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2562: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.2567: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.2568: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2574: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.2578: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2600: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.2605: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.2606: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2612: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.2616: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2637: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.2642: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.2643: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2649: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.2653: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2673: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.2678: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.2679: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2685: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.2689: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2708: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.2713: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.2714: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2720: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.2724: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2742: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.2747: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.2748: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2754: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.2758: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2775: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.2780: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.2781: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2787: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.2791: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2807: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.2812: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.2813: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2819: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.2823: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2838: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.2843: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.2844: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2850: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.2854: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2868: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.2873: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.2874: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2880: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.2884: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2897: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.2902: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.2903: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2909: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.2913: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2925: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.2930: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.2931: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2937: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.2941: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2952: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.2957: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.2958: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2964: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.2968: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2978: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.2983: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.2984: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.2990: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.2994: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3003: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.3008: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.3009: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3015: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.3019: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3027: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.3032: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.3033: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3039: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.3043: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3050: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.3055: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.3056: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3062: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.3066: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3072: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.3077: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.3078: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3084: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.3088: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3093: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.3098: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.3099: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3105: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.3109: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3113: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.3118: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.3119: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3125: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.3129: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3132: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.3137: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.3138: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3144: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.3148: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3150: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.3155: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.3156: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3162: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.3166: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3168: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.3169: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.3170: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.3171: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.3172: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.3173: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3174: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.3175: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.3176: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.3177: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.3178: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.3179: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.3180: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.3181: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.3182: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.3183: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3184: Error: Chain Y not found in ./Dataset/3eq3_Y.pdb
On alignment n.3188: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.3189: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3195: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.3199: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3203: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.3204: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3210: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.3214: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3217: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.3218: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3224: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.3228: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3230: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.3231: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3237: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.3241: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3243: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3244: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.3245: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.3246: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.3247: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.3248: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.3249: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.3250: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.3251: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.3252: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.3253: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3254: Error: Chain I not found in ./Dataset/5j4d_I_IA.pdb
On alignment n.3255: Traceback (most recent call last):
  File "runsara.py", line 335, in <module>
    atoms1=checkpdb(pdbfile1,chain1,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3256: Traceback (most recent call last):
  File "runsara.py", line 335, in <module>
    atoms1=checkpdb(pdbfile1,chain1,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3257: Traceback (most recent call last):
  File "runsara.py", line 335, in <module>
    atoms1=checkpdb(pdbfile1,chain1,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3258: Traceback (most recent call last):
  File "runsara.py", line 335, in <module>
    atoms1=checkpdb(pdbfile1,chain1,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3259: Traceback (most recent call last):
  File "runsara.py", line 335, in <module>
    atoms1=checkpdb(pdbfile1,chain1,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3260: Traceback (most recent call last):
  File "runsara.py", line 335, in <module>
    atoms1=checkpdb(pdbfile1,chain1,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3261: Traceback (most recent call last):
  File "runsara.py", line 335, in <module>
    atoms1=checkpdb(pdbfile1,chain1,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3262: Traceback (most recent call last):
  File "runsara.py", line 335, in <module>
    atoms1=checkpdb(pdbfile1,chain1,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3263: Traceback (most recent call last):
  File "runsara.py", line 335, in <module>
    atoms1=checkpdb(pdbfile1,chain1,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3264: Traceback (most recent call last):
  File "runsara.py", line 335, in <module>
    atoms1=checkpdb(pdbfile1,chain1,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3265: Traceback (most recent call last):
  File "runsara.py", line 335, in <module>
    atoms1=checkpdb(pdbfile1,chain1,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3270: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.3274: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3279: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.3283: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3287: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.3291: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3294: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.3298: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3300: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.3304: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3306: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.3307: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.3308: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.3309: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3310: Error: Chain Y not found in ./Dataset/3eq4_Y.pdb
On alignment n.3313: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3316: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3318: Traceback (most recent call last):
  File "runsara.py", line 336, in <module>
    atoms2=checkpdb(pdbfile2,chain2,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

On alignment n.3320: Traceback (most recent call last):
  File "runsara.py", line 335, in <module>
    atoms1=checkpdb(pdbfile1,chain1,atom)
  File "runsara.py", line 174, in checkpdb
    pdb=readPDBNucleicAcid(pdbfile,chain,atoms)
  File "Tools/NucleicAcidTools.py", line 1145, in readPDBNucleicAcid
UnboundLocalError: local variable 'rchainold' referenced before assignment

